language: node_js
node_js: node
services:
- mongodb
before_deploy: git config --global alias.stash 'stash -q'
deploy:
  provider: heroku
  api_key:
    secure: YfArUYg1LLpHiyP0r7tIfoKECJEk/sFrBw6eIcHzvmt/1TY8vYsdIutxjVMoiT5fZ3ynEwUhHY+SqDpnELG+hLI5pJLOp3IwLZz89r8X5V+ZiMw0R3HVMkK+bX9xvqzYs8YgTqH56QQ27iBXxDs52dh8mZiRWT9BrnedzJQH2CUjwTYmkfgKWxJz6QBZiGjGOIDnnkPIbGqC1P4+r/hpzhxlxYhF6zYBnL59Xo9kqWLqlp+trd9DPM05+oPm7Nk5MF02u6czYGDmkMRaUGkPjJogA1H6Gx2rjjpBQuuUIOciKw5C3HrSiw3pK+aPonaPc3GYOyTyCV9E5FyhaV5W6d6xlA05dMzgtZfjRqPuptVnkrpuw3NRqkzwHRtam4jCZvjgl9/0j7tzubzlsLsc8xW/lARJlaMb8diHn5Z+rfbI/WJekfB+Q+RiOFktyWOrMoxHJe9tsuKIdw2IfJVzn7+Olxbug/h8EiZzIvmR6kB2WqC3ARVg+pSuBcVoJlaqWLy2nis7JbUHAKD2xWqdosIgXb4gmMUt1CQvk/CMIbwsWhDxLeSOQqL9r2SLtxZ/whSuUsRTw8Y/K3gis7nEkUXsjOHr5G5V/+lwJGW3pmZpVD/XhWqhOelqXJ+IivAl02DVExoEVlmlKaplref8GpYJvuMroIyRhxPICtKpbgE=
    # secure: Qhbo0HipsyXFU0PmMpNPBxLK79GtLHUT0UOYFNhwKkmAzcxBnoX/8ghdwoN7oufBxMKEayuIQlzVLB3zn22N8p40znq2XBPR4EwLKIApto5reBEhl5yoLID9jOH6Nw1dOpQ90lZMi4wHBAM20pMZc86FPUJ/5nvjVVCidLnQR6sfeKpydXFD/B72O2/LJJopibRCXlQ8mRbZZ/wgwbvwPfRgE6S16GiB3R4YaOL5IfuWrLixkWz+hfUO9Jpj+j3YuqEAwKCHyBkv5UeBGaUkWXUguHnxRAD74FVbLi+PAkAuQuyXwkCOlvRmRRyjH3T5DA3DXwmLoyGmwWFixcGN8hFDR3/wIiFC4VB0+aYrMFwngchMnxOaIJT1VY9CXeXm+FmrGNAPvOdB0nLPL01sXVY0pti1+KkKgq9Rz31O4SjII8eKEv/5iYOAaIeow4yGNUlt2SKGjWU32dSsO7JmaegLt5dNZLhfnrLgAGVmfrNdztLKAjeNO1zQpcRpYhhvdH0/n/T1GsIxdWvJcwwDco0+D3eNpIJq8FB/Os9aUEc2s+PXAGV1BJ/FKmTdGOXGDYfP4GNKTJtHwH7o/Rid8Vi4HsykjrBK/pLM9sfU0PWYHoX4tE6my11HIMxQKj0XOSg1DaE/Yt8Am5gHkmx1WvlpfkTeFtzRokuKoEqLKUI=
  app: track-life
  # app: afternoon-refuge-57090
  on:
    repo: codeannie/track-life
