language: node_js
node_js: node
services:
- mongodb
before_deploy: git config --global alias.stash 'stash -q'
deploy:
  provider: heroku
  api_key:
    secure: Qhbo0HipsyXFU0PmMpNPBxLK79GtLHUT0UOYFNhwKkmAzcxBnoX/8ghdwoN7oufBxMKEayuIQlzVLB3zn22N8p40znq2XBPR4EwLKIApto5reBEhl5yoLID9jOH6Nw1dOpQ90lZMi4wHBAM20pMZc86FPUJ/5nvjVVCidLnQR6sfeKpydXFD/B72O2/LJJopibRCXlQ8mRbZZ/wgwbvwPfRgE6S16GiB3R4YaOL5IfuWrLixkWz+hfUO9Jpj+j3YuqEAwKCHyBkv5UeBGaUkWXUguHnxRAD74FVbLi+PAkAuQuyXwkCOlvRmRRyjH3T5DA3DXwmLoyGmwWFixcGN8hFDR3/wIiFC4VB0+aYrMFwngchMnxOaIJT1VY9CXeXm+FmrGNAPvOdB0nLPL01sXVY0pti1+KkKgq9Rz31O4SjII8eKEv/5iYOAaIeow4yGNUlt2SKGjWU32dSsO7JmaegLt5dNZLhfnrLgAGVmfrNdztLKAjeNO1zQpcRpYhhvdH0/n/T1GsIxdWvJcwwDco0+D3eNpIJq8FB/Os9aUEc2s+PXAGV1BJ/FKmTdGOXGDYfP4GNKTJtHwH7o/Rid8Vi4HsykjrBK/pLM9sfU0PWYHoX4tE6my11HIMxQKj0XOSg1DaE/Yt8Am5gHkmx1WvlpfkTeFtzRokuKoEqLKUI=
  app: afternoon-refuge-57090
  on:
    repo: codeannie/track-life
