language: node_js
node_js: node
services:
- mongodb
before_deploy: git config --global alias.stash 'stash -q'
deploy:
  provider: heroku
  api_key:
    secure: G8inz6AVAG90TmcoCnetwbqjAUbm9Sfgbcqzx4HBtuxAo12/4OjxfUpDJfivXnGEuXAa0iGas/pI+BmgFfyi1/Sweqrv6HPlkgDKTxDUzIpiapXDDd9aJiRxGjNyEsl0kZuBZ0Oze6I9V2KVRRMchEirSTonmreOMUvRMHsT9XyY3GfI9TqsJGURm7hkzTBgy09KapMNSQlLRN+sSxzjdYiMVwgYYfC7E5Hkvc4dRALgJObcNkxzhZ0QMPVatKCG/FvEWL4cXvqE3Tfme5T+z2XGw4dGCKwp9Ryl240KIy9bIYC5wKg9pZc0SugU4sDX0Y8dJBM/TXEXQUOy9zAK9ntA0K6Es7D1si4q7yJ12w1V3GEf98BJWhIlqk1YW8Mw8IrBp/S+PYOjwbknIy64Peji7M3wJdoA90F7MAwwC3NsEehgTXwhBHfUY1EFnU2AkGnfKzfDw9ZEY3Lf8IE6I0U2y+PTPYqZOeF3YP/7i/pyBW3E6S8Pjz554dPst5UHWmeDvCgJd2CjQpJncwx8HcyQqHtCZJ4LmC/EeCFXnBjIzih2WmRE9o2g1b0e0FkSVyUoANu20yOL7Iydq8GMqoG2bk6zM6WigrkBd8uRighl2P5MZKIMvzrwYa3tlJmA6PmVWklxOgb7pdaa5TyRl6evTYq0BvtcK4Q5XVhZ2Mw=
  app: track-life
  on:
    repo: codeannie/track-life
